### ISSUE TITLE
Feature request: default value for a variable

### ISSUE THREAD

**Issue by QiangF** [lucaswerkmeister/cheats#10]
Hello Sir,
In some cases make a default value for a prompt variables can save typing. Such as

    chown -R $user $file

The $user can have a most often user name. Also if the command option is a variable, the most often used one can be the default.
What do you think?

**Comment by lucaswerkmeister** [comment]
With the changes in 2e463d3, you can use the “Use Default Values” parameter expansion for this:
```bash
chown -R ${user:-someone} $file
```
Then, when you leave the `user` blank on the promt, the default value will be used.
