### ISSUE TITLE
auto complete file or directory name?

### ISSUE THREAD

**Issue by QiangF** [lucaswerkmeister/cheats#7]
Hello Sir,
what about making a default parameter $filenames, if a command has that parameter, after the prompt, auto complete the common part of each file name using tab?
Thank you for this handy tool.

**Comment by lucaswerkmeister** [comment]
We can use `read -e` to read with `readline`, which supports tab completion. But I’m not sure if I want to restrict this to a single variable name. What if we just turn this on for all variables?

**Comment by QiangF** [comment]
That will be cool. But it may add too many irrelevant candidates and you need to press more tabs to get you want. Maybe add the default value for a prompt area if that prompt doesn't asking for file or directory names.
Thank you!

**Comment by lucaswerkmeister** [comment]
I don’t understand what you mean. Why would you need to press more tabs? And what would the default value be?

**Comment by QiangF** [comment]
Take this example for cheat "chmod a"

    change file attributes
    chmod $options $filenames
    options; attibute setting such as "666", "755", "644" or "-R 666" (add -R if file name is a directory)
    file: file names

there are two prompt, the first one has several options that may
benifit from auto completion, if you add "666", "-R 666" to the
candidate list, the second one need a file or directory name, and
if you "have a file named 678, and the filename candidates and the
attribute candidate 666 are mixed, type 6 wo't auto complete 678,
if will display all two candidates, if the completion candidate
is prompt aware, when you at a filename prompt, it will instantly
gives you 678. Just a silly example.

**Comment by lucaswerkmeister** [comment]
Okay, but… if the argument you’re entering isn’t a filename… just don’t use tab completion :)

I don’t think full programmable autocompletion is possible here – I don’t know how to tell readline which compspec to use. I’ll change it to `read -e`, and I think that’ll be enough for now.
