### ISSUE TITLE
cheats not working for convert

### ISSUE THREAD

**Issue by QiangF** [lucaswerkmeister/cheats#9]
Hello Sir,
can you help me get the following cheat right?

    Scale to max dimension,keep aspect ratio
    convert "$original_file -resize $max_dim $new_file"
    original_file:original file name with extension
    new_file:new file name with (new) extension
    max_dim:max image size in pixel

Thank you!

**Comment by lucaswerkmeister** [comment]
You should probably quote only individual arguments, not the entire command. Try this:
```sh
Scale to max dimension,keep aspect ratio
convert "$original_file" -resize "$max_dim" "$new_file"
original_file:original file name with extension
new_file:new file name with (new) extension
max_dim:max image size in pixel
```
If that doesn’t work, it’s possible that the underscores in the variable names cause problems. You could try `originalFile` instead of `original_file`.

**Comment by QiangF** [comment]
Both of your suggestion don't work. I got this error.

    convert: invalid argument for option `-resize':  @ error/convert.c/ConvertImageCommand/2553.

The command works if I substitute the values and run it in the terminal.

**Comment by lucaswerkmeister** [comment]
It seems to work fine for me. Which values are you using?

**Comment by QiangF** [comment]
Must be some problem in my environment. It works on another computer. Thank you for your help!

**Comment by lucaswerkmeister** [comment]
Alright, then I’ll close this issue – you’re welcome :)

**Comment by lucaswerkmeister** [comment]
But perhaps you want to create a pull request for this cheat? It sounds useful!

**Comment by QiangF** [comment]
I am still learning to use git. I will share my cheats later.
Cheers!
